package com.cheesymountain.woe.work;

import com.cheesymountain.woe.Occupationable;
/*=============================================================
 * Copyright 2012, Cheesy Mountain Production
 * 
 * This file is part of World of Everbies.
 * 
 * World of Everbies is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * World of Everbies is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with World of Everbies.  If not, see <http://www.gnu.org/licenses/>.
================================================================*/

/**
 * The abstract class to be extended by all classes that
 * are to be treated as works. It contains getters and the
 * constructor to be used.
 * 
 * @author Karl-Agnes
 * 
 */
public abstract class Work implements Occupationable{

	private int time, salary, happinessModifier, healthModifier, minutesWorking, starvationModifier,
			strengthReq, staminaReq, intelligenceReq;
	
	/**
	 * The public constructor that is called from all subclasses with the specific
	 * values of that subclass.
	 * 
	 * @param time the amount of hours the Everbie will spend working
	 * @param salary the amount of money your Everbie will earn
	 * @param happinessModifier an int describing how the Everbies happiness will be
	 * 		affected from working
	 * @param healthModifier an int describing how your Everbies health will be affected
	 * 		from working
	 */
	public Work(int time, int salary, int happinessModifier, int healthModifier, int minutesWorking,
			int starvationModifier, int strengthReq, int staminaReq, int intelligenceReq){
		this.time = time;
		this.salary = salary;
		this.happinessModifier = happinessModifier;
		this.healthModifier = healthModifier;
		this.minutesWorking = minutesWorking;
		this.starvationModifier = starvationModifier;
	}
	
	/**
	 * A method for returning the name of the work session
	 * 
	 * @return the name of the task
	 */
	public abstract String getName();
	
	/**
	 * A method for returning the time of the work session
	 * 
	 * @return the time it takes to complete the task
	 */
	public int getTime(){
		return time;
	}
	
	/**
	 * A method for returning the salary of the work session
	 * 
	 * @return the amount of money generated by the task
	 */
	public int getSalary(){
		return salary;
	}
	
	/**
	 * A method for returning the happinessModifier of the work session
	 * 
	 * @return the modifier for the Everbies happiness
	 */
	public int getHappinessModifier(){
		return happinessModifier;
	}
	
	/**
	 * A method for returning the healthModifier of the work session
	 * 
	 * @return the modifier for the Everbies health
	 */
	public int getHealthModifier(){
		return healthModifier;
	}
	
	/**
	 * A method for returning the number of minutes the work session requires
	 * 
	 * @return the number of minutes the Everbie is at work
	 */
	public int getMinutesWorking(){
		return minutesWorking;
	}
	
	/**
	 * A method for returning how much starvation the Everbie suffers from the current work session
	 * 
	 * @return the starvationModifier of the work session
	 */
	public int getStarvationModifier(){
		return starvationModifier;
	}
	
	/**
	 * A getter for the Strength Requirement of this Work.
	 * 
	 * @return the least amount of strength required
	 */
	public int getStrengthReq(){
		return strengthReq;
	}
	
	/**
	 * A getter for the Stamina Requirement of this Work.
	 * 
	 * @return the least amount of stamina required
	 */
	public int getStaminaReq(){
		return staminaReq;
	}
	
	/**
	 * A getter for the Intelligence Requirement of this Work.
	 * 
	 * @return the least amount of intelligence required
	 */
	public int getIntelligenceReq(){
		return intelligenceReq;
	}
}
